[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
python = "latest"
neovim = "latest"
fzf = "latest"
bat = "latest"
ripgrep = "latest"
direnv = "latest"
sops = "latest"
